### ISSUE TITLE
Light mode channel sidebar text is hard to see against the background

### ISSUE THREAD

**Issue by makrcat** [maenDisease/Outlook#5]
<img align="left" width="189" alt="Screenshot 2023-08-17 at 9 50 59 AM" src="https://github.com/maenDisease/Outlook/assets/108638101/3479deb6-8a22-455e-b766-2d4c9ed1068a">

Hi! 

I noticed that the unread channels were pretty hard to see against the background in light mode. In addition, the channel groups text also blends into the background when hovered over. 

<< An example

It'd be really nice if you could fix that! :)

**Comment by makrcat** [comment]
Basically, it's a bit different than the image in the readme file

**Comment by maenDisease** [comment]
![image](https://github.com/maenDisease/Outlook/assets/90428263/e1b2d937-3382-4c1a-9a8c-cede8d96a6a4)
I can't replicate the issue, could you send your theme file

**Comment by makrcat** [comment]
Github isn't letting me upload a file for some reason, but I think I got the file from here https://betterdiscord.app/theme/Outlook

Maybe it's an outdated file?

**Comment by maenDisease** [comment]
that wouldn't be the reason

**Comment by makrcat** [comment]
oh ok
I tried getting it from here https://github.com/maenDisease/Outlook/blob/deploy/Outlook.theme.css but nothing changed :(
Does it matter that I'm on macos?

**Comment by maenDisease** [comment]
I just tested on macos and there were no issues, check if you have other custom css causing the issue

**Comment by makrcat** [comment]
Ohh okay, so I figured out the issue. I had discord's "dark sidebar" turned on, so the sidebars were all being wonky
It works really well now! Thank you so much :)
